### PR TITLE
Remove wrong hint

### PR DESCRIPTION
**Pull request by kinongo**
According to #1 

Sorry for not following step-by-step.

For the [Hacktoberfest Global Meetup Hsinchu](https://hacktoberfest.digitalocean.com) today, I pull request first on the mini-hackathon during the event.

I will finish up the rest of steps after being a contributor to this repository.

------

### 🆕🐥☝ First Timers Only.
This issue is reserved for people who never contributed to Open Source before. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

[About First Timers Only](http://www.firsttimersonly.com/).

### 🤔 What you will need to know.
Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step
* [x]  🙋 **Claim this issue**: Comment below.
  Once claimed we add you as contributor to this repository.
* [x]  👌 **Accept our invitation** to this repository. Once accepted, assign yourself to this issue
* [x]  📝 **Update** the file [getting-started/your-first-template.md](https://github.com/nebrelbug/squirrelly.js.org/blob/master/getting-started/your-first-template.md) in the `squirrelly.js.org` repository (press the little pen Icon) and edit the line as shown below.

```diff
@@ -14,10 +14,6 @@ var Sqrl = require("squirrelly")
//Or, if you're in the browser, Sqrl is already global
 
-{% hint style="info" %}
-Don't import as a `const,`otherwise you won't be able to define your own helpers and filters.
-{% endhint %}
-

## 2. Create a Template
 
```text
```

* [x]  💾 **Commit** your changes
* [x]  🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.
2. You can [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/)

* [ ]  🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions
Leave a comment below!
 
This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).

### CODE REVIEW

**Review by bgub — CHANGES_REQUESTED** [review]
This looks good, just don't delete line 13. Thanks!

**Comment by kinongo** [comment]
Hi @nebrelbug, I have delete line 13 directly in this Pull Request.

I am not sure am I doing right🤔❓
Or I need to pull another request.

**Review by bgub — CHANGES_REQUESTED** [review]
This looks good! Just undelete the comments that were on lines 13 and 14 :). Then I'll merge the pull request. Thanks!

**Comment by kinongo** [comment]
Hi, @nebrelbug. I thought I have finished #2 🤔❓
You say you will merge the pull request. Or I have to do something else?

**Comment by bgub** [comment]
@micky619 you actually didn't need to delete lines 13 and 14. As soon as you undelete them, I'll merge. Thanks!

**Pull request closed without merging**
